#SPDX-License-Identifier: MIT-0
---
- name: Check if kubeadm is installed
  ansible.builtin.command: which kubeadm
  register: kubeadm_check
  ignore_errors: yes  # Prevents failure if 'which' doesn't find kubeadm
  changed_when: false

- name: revert of changes made to this host by 'kubeadm init' or 'kubeadm join' 
  ansible.builtin.command:
    cmd: "kubeadm reset -f"
  when: kubeadm_check.rc == 0

- name: Cleanup k8s cluster directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ kube_cluster_dirs }}"
  when: kubeadm_check.rc == 0