#SPDX-License-Identifier: MIT-0
---
- name: Update repositories cache and install "k8s" package
  ansible.builtin.apt:
    name: haproxy # Install HAProxy package
    update_cache: yes
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'    
  notify: Restart service haproxy # Notify handler to restart containerd

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers  

