#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/k8s_packages
- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: Download Kubernetes GPG key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key
    dest: /tmp/kubernetes-temp.key
    validate_certs: yes

- name: Convert and install key
  ansible.builtin.command: >
    gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-temp.key
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg  # Idempotency

- name: Cleanup temp file
  ansible.builtin.file:
    path: /tmp/kubernetes-temp.key
    state: absent    

- name: Overwrite entire file content
  ansible.builtin.copy:
    content: |
            deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ /
    dest: /etc/apt/sources.list.d/kubernetes.list
    mode: '0644'
- name: Update repositories cache and install "k8s" package
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - kubectl
    - kubelet
    - kubeadm

- name: Hold kubeadm properly
  ansible.builtin.command: apt-mark hold kubeadm kubectl kubelet
  args:
    creates: /etc/apt/held_kubeadm  # Makes it idempotent
  become: yes
  changed_when: false  # Prevents false "changed" states
