#SPDX-License-Identifier: MIT-0
---
- name: Run kubeadm token create and capture output
  ansible.builtin.command: " kubeadm token create --print-join-command"
  register: command_result  # Saves ALL output here    
  when: inventory_hostname == groups['super-master'][0]

- name: Get raw certificate key output
  command: "kubeadm init phase upload-certs --upload-certs"
  register: cert_key_raw
  when: inventory_hostname == groups['super-master'][0]
  
- name: Extract ONLY the certificate key (last line)
  ansible.builtin.set_fact:
    kubeadm_cert_key: "{{ cert_key_raw.stdout_lines[-1] }}"  # Takes the last line
  when: inventory_hostname == groups['super-master'][0]

- name: Construct master join command
  ansible.builtin.set_fact:
    master_join_command: >-
      {{ hostvars[groups['super-master'][0]]['command_result']['stdout'] }}
      --control-plane
      --certificate-key {{ hostvars[groups['super-master'][0]]['kubeadm_cert_key'] }}
      --apiserver-advertise-address {{ node_IP }}  
  when: inventory_hostname in groups['master-nodes']

- name: debug
  debug:
    msg: "Master join command: {{ master_join_command }}"
  when: inventory_hostname in groups['master-nodes']

- name: Join master nodes
  command: "{{ master_join_command }}"
  args:
    creates: "/etc/kubernetes/admin.conf"  # Prevents re-runs
  when: inventory_hostname in groups['master-nodes']